package com.mycompany.bms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@Entity
//Marks the class as  a JPA entity representing a database tabla
@Table(name = "admin")
//Makes table named admin inside our database
public class Admin extends BaseEntity {

    private static final long serialVersionUID = 1L;

    @Column(name = "name", nullable = false)
    @NotEmpty(message = "Name cannot be empty")
    @Size(min = 5, max = 30, message = "Full name should be at least 5 characters")
    @Pattern(regexp = "^[a-zA-Z ]+$", message = "Name should be a valid string")
    private String name;

    @Column(name = "username", nullable = false, unique = true)
    @NotEmpty(message = "Username cannot be empty")
    @Email(message = "Username must be a valid email address")
    private String username;

    @Column(name = "password", nullable = false)
    @NotEmpty(message = "Password cannot be empty")
    @Size(min = 6, message = "Password must be at least 6 characters long")
    private String password;

    //Making empty constructor
    public Admin() {

    }

    //Making costructor with all attributes except ID as ID is autogenerated
    public Admin(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }

    //Making getters and setters method
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    @Override
    public String toString() {
        return "Admin{" + "id=" + getId() + ", name=" + name + ", username=" + username+ '}';
    }
}
