package com.mycompany.bms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
//Marks the class as  a JPA entity representing a database tabla
@Table(name="admin")
//Makes table named admin inside our database
public class Admin{
    
    @Id
//    Defines that it is id for the table
    @GeneratedValue(strategy=GenerationType.IDENTITY)
//    Automatically generates unique IDs for th entity using an auto-increment column
    
    private Long id;
    
    @Column(name="name", nullable=false)
    private String name;
    
    @Column(name="username", nullable=false, unique=true)
    private String username;
    
    @Column(name="password",nullable=false)
    private String password;
    
    //Making empty constructor
    public Admin()
    {
        
    }
    
    //Making costructor with all attributes except ID as ID is autogenerated
    public Admin(String name, String username, String password)
    {
        this.name=name;
        this.username=username;
        this.password=password;
    }
    
    //Making getters and setters method
    
    public Long getId()
    {
        return id;
    }
    
    public void setId(Long id)
    {
        this.id=id;
    }
    
    public String getName()
    {
        return name;
    }
    
    public void setName(String name)
    {
        this.name=name;
    }
    
    public String getUsername()
    {
        return username;
    }
    
    public void setUsername(String username)
    {
        this.username=username;
    }
    
    public String getPassword()
    {
        return password;
    }
    
    public void setPassword(String password)
    {
        this.password=password;
    }
}